### ISSUE TITLE
model classes

### ISSUE THREAD

**Issue by stgm** [NielsPann/SabSound#2]
Je moet model classes gebruiken; zorg dat je dit vandaag in je design doc verwerkt

close deze issue als je het begrepen/gefixt hebt

**Comment by NielsPann** [comment]
Bedoel je hier de model class diagram mee die wij ook bij Appstudio hebben gemaakt? Ik kreeg te horen van de begeleiders dat wat ik nu had voldoende was. Maar ik zal deze vandaag dan maken.

**Comment by NielsPann** [comment]
het is duidelijk!
